apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        imagePullPolicy: Never
        image: my_wordpress
        ports:
        - containerPort: 5050
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  type: LoadBalancer
  selector:
    app: wordpress
  ports:
    - port: 5050
      protocol:  TCP
      targetPort: 5050
