FROM alpine:3.12

EXPOSE 3306

RUN apk update --no-cache
RUN apk upgrade --no-cache
RUN apk add mysql --no-cache
RUN apk add mysql-client --no-cache

RUN mkdir -p /run/mysqld
COPY ./srcs/my.cnf ./etc/my.cnf.d/
COPY ./srcs/setup.sh /

RUN chmod +x /setup.sh
# Read only 0444
RUN chmod 0444 /etc/my.cnf.d/my.cnf

ENTRYPOINT ["/bin/sh", "/setup.sh"]