
FROM alpine:latest

# Expose port
EXPOSE 3306

# Install and Update utils
RUN apk update --no-cache
RUN apk upgrade --no-cache
RUN apk add mysql --no-cache
RUN apk add mysql-client --no-cache
RUN mkdir -p /run/mysqld

# Install Telegraf
RUN apk add telegraf --repository http://dl-cdn.alpinelinux.org/alpine/v3.13/community

# Copy configuration
COPY ./srcs/my.cnf ./etc/my.cnf.d/
COPY ./srcs/start_mysql.sh /
COPY ./srcs/telegraf.conf /etc/telegraf/

RUN chmod 0444 /etc/my.cnf.d/my.cnf

# Access setup
COPY ./srcs/start_mysql.sh /
RUN chmod +x /start_mysql.sh

ENTRYPOINT ["/bin/sh", "/start_mysql.sh"]