FROM alpine:3.12

EXPOSE 80 443 22

RUN apk -U update --no-cache
RUN apk add nginx --no-cache
RUN apk add openssl --no-cache
RUN apk add openssh --no-cache
RUN apk add telegraf --repository http://dl-cdn.alpinelinux.org/alpine/v3.13/community
RUN adduser -D -g 'www' www
RUN mkdir /www
RUN chown -R www:www /var/lib/nginx
RUN chown -R www:www /www
RUN adduser -D admin
RUN echo "admin:password" | chpasswd 
RUN openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/ssl/private/nginx-selfsigned.key -out /etc/ssl/certs/nginx-selfsigned.crt \
    -subj "/C=FR/ST=ILEDEFRANCE/L=PARIS/O=OrgName/OU=IT Department/CN=42student"
RUN ssh-keygen -A
RUN rm /etc/nginx/nginx.conf

COPY ./srcs/telegraf.conf /etc/telegraf/
COPY srcs/nginx.conf /etc/nginx/nginx.conf
COPY srcs/start_nginx.sh /
RUN chmod +x /start_nginx.sh
RUN mkdir -p /run/nginx
ENTRYPOINT ["/bin/sh", "/start_nginx.sh"]