FROM alpine:3.12

EXPOSE 80 443 22

# Install Nginx packages
RUN apk -U update --no-cache
RUN apk add nginx --no-cache
RUN apk add openssl --no-cache
RUN apk add openssh --no-cache
RUN apk add telegraf --repository http://dl-cdn.alpinelinux.org/alpine/v3.13/community
RUN adduser -D -g 'www' www
RUN mkdir /www
RUN chown -R www:www /var/lib/nginx
RUN chown -R www:www /www
RUN ssh-keygen -A

# Generate ssl certificate
RUN openssl genrsa -des3 -passout pass:1234 -out server.pass.key 2048 && \
    openssl rsa -passin pass:1234 -in server.pass.key -out server.key && \
    rm server.pass.key && \
    openssl req -new -key server.key -out server.csr \
        -subj "/C=FR/ST=ILEDEFRANCE/L=PARIS/O=OrgName/OU=IT Department/CN=42student" && \
    openssl x509 -req -days 365 -in server.csr -signkey server.key -out server.crt

COPY ./srcs/telegraf.conf /etc/telegraf/
COPY srcs/nginx.conf /etc/nginx/nginx.conf
COPY srcs/start_nginx.sh /
RUN chmod +x /start_nginx.sh
RUN mkdir -p /run/nginx
ENTRYPOINT ["/bin/sh", "/start_nginx.sh"]